// SysEx manufacturer ID of Behringer GmbH
const SYSEX_MANUFACTURER = [0x00, 0x20, 0x32];

const ROTARY_MODE_COARSE = 0;
const ROTARY_MODE_FINE = 1;

const DEFAULT_VALUE_MASTER_FADER = 96;
const DEFAULT_VALUE_ROTARY = 63;
const DEFAULT_VALUE_BUTTON = false;
const DEFAULT_VALUE_VARIANT = 0;
const DEFAULT_ROTARY_MODE = ROTARY_MODE_COARSE;
const DEFAULT_VALUE_RUN_PATTERN_DEVICES = false;
const DEFAULT_VALUE_BYPASS_ALL_FX = false;

const DEFAULT_SCENE = {
  rotary1: DEFAULT_VALUE_ROTARY,
  rotary2: DEFAULT_VALUE_ROTARY,
  rotary3: DEFAULT_VALUE_ROTARY,
  rotary4: DEFAULT_VALUE_ROTARY,
  rotary5: DEFAULT_VALUE_ROTARY,
  rotary6: DEFAULT_VALUE_ROTARY,
  rotary7: DEFAULT_VALUE_ROTARY,
  rotary8: DEFAULT_VALUE_ROTARY,
  button1: DEFAULT_VALUE_BUTTON,
  button2: DEFAULT_VALUE_BUTTON,
  button3: DEFAULT_VALUE_BUTTON,
  button4: DEFAULT_VALUE_BUTTON,
  button5: DEFAULT_VALUE_BUTTON,
  button6: DEFAULT_VALUE_BUTTON,
  button7: DEFAULT_VALUE_BUTTON,
  button8: DEFAULT_VALUE_BUTTON,
  variantA: DEFAULT_VALUE_VARIANT,
  variantB: DEFAULT_VALUE_VARIANT,
  masterFader: DEFAULT_VALUE_MASTER_FADER,
};

module.exports = {
  SYSEX_MANUFACTURER,
  ROTARY_MODE_FINE,
  ROTARY_MODE_COARSE,
  DEFAULT_VALUE_ROTARY,
  DEFAULT_VALUE_VARIANT,
  DEFAULT_VALUE_MASTER_FADER,
  DEFAULT_VALUE_BUTTON,
  DEFAULT_ROTARY_MODE,
  DEFAULT_VALUE_RUN_PATTERN_DEVICES,
  DEFAULT_VALUE_BYPASS_ALL_FX,
  DEFAULT_SCENE,
};
